### ISSUE TITLE
MI-AFP Homework

### ISSUE THREAD

**Issue by Taskkill** [Taskkill/FeenyML#1]
## Implementation of the FeenyML language
- [x] Lexer + Parser - Done
- [x] AST Interpreter - Mostly done
- [x] Bytecode Interpreter - Partially done
- [x] Bytecode Compiler - Partially done
- [ ] Garbage Collector  - Was not done in the class at the end
- [ ] Bytecode Serializer  - Was not done in the class at the end
- [ ] Bytecode Deserializer (Parser) - Was not done in the class at the end

### TODOs for AFP semestral project:
- [x] testing
- [x] documentation with examples
